### ISSUE TITLE
Enum Values with value Zero are not marshalled as Json

### ISSUE THREAD

**Issue by davew1977** [alvaroloes/enumer#10]
I have an enum like 
```
type Fruit byte

const (
	APPLE         Fruit = iota
	PEAR
)
```
when serialising a value `APPLE` to json I would expect the value to appear in the output json. However, the value does not appear, presumably because it is `0` under the hood

Replacing `Fruit = iota` with `Fruit = iota + 1` means APPLE gets outputted as expected

I'm new to Go from java, so there may be good reason why this is so, but it was surprising for me, so, if you don't think it should be fixed, perhaps it's worth a mention in the documentation

**Comment by THE108** [comment]
Hi!

I've just tried to reproduce it but it seems everything works fine:

```
package main

import (
        "fmt"
        "encoding/json"
)

type Fruit byte

const (
        APPLE         Fruit = iota
        PEAR
)

type A struct {
        Fruit Fruit
        Weight int
}

func main() {
        a := A{
                Fruit: APPLE,
                Weight: 10,
        }

        msg, _ := json.Marshal(&a)
        fmt.Println(string(msg))
}
```


Enum related code was generated with `enumer -json -type Fruit fruit_enum.go`.

```
$ go run fruit_enum.go fruit_string.go
{"Fruit":"APPLE","Weight":10}
```

**Comment by alvaroloes** [comment]
@davew1977 Hi! Are you still having this issue?
(BTW, thanks @THE108 for testing!)

**Comment by davew1977** [comment]
hi, it's been a while and I'm not working with go at the moment, and don't have my old environment to hand - but @THE108 's test looks solid... I wonder if maybe i did not use the `-json` flag

**Comment by alvaroloes** [comment]
That could be the case. I'll close this and if you get to work with Go again and see the same issue, please feel free to reopen it. 
Thanks!
