### ISSUE TITLE
Request support ENUM list for SQL Check function

### ISSUE THREAD

**Issue by GJRTimmer** [alvaroloes/enumer#11]
I would like to request a function which returns all the ENUMS as comma separated list.

# Introduction Information:
See the following example from stackoverflow: http://stackoverflow.com/a/17203007
```sql
CREATE TABLE prices (
 id INTEGER PRIMARY KEY,
 pName TEXT CHECK( LENGTH(pName) <= 100 ) NOT NULL DEFAULT '',
 pType TEXT CHECK( pType IN ('M','R','H') ) NOT NULL DEFAULT 'M',
 pField TEXT CHECK( LENGTH(pField) <= 50 ) NULL DEFAULT NULL,
 pFieldExt TEXT CHECK( LENGTH(pFieldExt) <= 50 ) NULL DEFAULT NULL,
 cmp_id INTEGER NOT NULL DEFAULT '0'
)
```

Regards of database system, (MySQL, PostgreSQL, SQLite, Microsoft SQL Server) it is quite common to use a statement involving ```IN```.

# Request:
I would like to do the following.
Generate a ENUM for a const with enumer, with -json, -sql. Then I would like to have a function which returns the ENUMS as a comma separated list so I can place it dynamically within SQL statements with Sprintf. This way I only have to re-generate the ENUM and the SQL statement will also include the new ENUM within either a ```CHECK``` statement like above or as a ```IN``` statement.

Example (ENDUSER):

```go
func GetUser() interface{} {
    return db.Exec(fmt.Sprintf(`
        SELECT * 
        FROM USERS 
        WHERE 
            USERNAME=$1 
        AND 
        TYPE IN ('%s')`, enumer.SQLList()), username)
}
```

Function name for this request can be chosen better :-)

P.S. Above code is just a example.

**Comment by alvaroloes** [comment]
Hi! Thank you very much for filling the issue.
Just wanted to let you know that I've been very busy this year, but now I'm starting to have time again. So I expect to have time to review this soon 😉

**Comment by GJRTimmer** [comment]
Could it be possible for you to run a diff against my master branch. I've
updated a lot.

I think you will like it.

**Comment by alvaroloes** [comment]
I haven't had the time to check your master branch but, from the top of my mind, this is what I think:
- I would like to avoid adding things that are specific to certain projects or areas (other than "Enums"), as it would complicate a lot its maintenance and reusability.
- After reading your issue, I think that what you are looking for is something like the `enum.values()` method in Java which returns an array with all the values of the enum. I think this is a good addition, as it is general and tightly copuled with Enums (and nothing else).

So you could call the `values()` method and do what you want with the array of values, like converting them to strings and joining the values togheter as a coma-separated list.

Let's see if I can buy some extra time and add this method 😉

**Comment by GJRTimmer** [comment]
Thanks, I really hope that you can find some time to check my master, or at
least run a compare, I've made a lot of improvements.

**Comment by alvaroloes** [comment]
The new version of `enumer` has some additions that can be used to achieve this. 
Your example would be like this (not checked):
```go
// Assuming the enum is called UserTypes
func GetUser() interface{} {
    userTypesString := strings.Trim(strings.Replace(fmt.Sprint(UserTypesValues()), " ", "','", -1), "[]")
    return db.Exec(fmt.Sprintf(`
        SELECT * 
        FROM USERS 
        WHERE 
            USERNAME=$1 
        AND 
        TYPE IN ('%s')`, userTypesString), username)
}
```
Thanks for your feedback and code!
