### ISSUE TITLE
Support for multiple transform targets.

### ISSUE THREAD

**Issue by itsjamie** [alvaroloes/enumer#17]
For example: 
JSON would transform to snake_case
String() would transform to kebab-case

Therefore "cs-uri-stem" would be defined as `var CsUriStem` and run with a transform of kebab-case, but would marshal as `cs_uri_stem`.

**Comment by alvaroloes** [comment]
Hi! Thank you very much for filling the issue!
Just wanted to let you know that I've been very busy this year, but now I'm starting to have time again. So I expect to have time to review this soon 😉

**Comment by alvaroloes** [comment]
Hey! Thanks again.

Ok, this could complicate the `enumer` interface a lot and I'm not sure if there are many use cases for this. Besides, I don't think this is tightly coupled with enums -> you can always do those transformations in your code without the need to add it to the generated code.

So I'm going to close this issue as I don't think this functionality is general enough to be included in `enumer`.
