### ISSUE TITLE
can't find import

### ISSUE THREAD

**Issue by tcurdt** [alvaroloes/enumer#24]
Seems like I cannot use any imports with `enumer`. I have to uncomment all for a successful run.
The project builds fine otherwise.

```
enumer: checking package: main.go:5:2: could not import gopkg.in/yaml.v2 (can't find import: "foo/vendor/gopkg.in/yaml.v2")
```

My setup:
```
$ go version
go version go1.9.2 darwin/amd64
$ ls -l -d $GOPATH/src/foo/vendor/gopkg.in/yaml.v2/
drwxr-xr-x  16 tcurdt  staff  544 Dec 12 03:06 .../src/foo/vendor/gopkg.in/yaml.v2/
```

**Comment by alvaroloes** [comment]
Hum... This could be caused because of the new version of Go. I'll take a look.

Thanks for reporting!

**Comment by alvaroloes** [comment]
This should be fixed now. Please do some test and let me know if you keep finding the issue (please reopen if so)
