### ISSUE TITLE
could not import sync

### ISSUE THREAD

**Issue by kochurovro** [alvaroloes/enumer#44]
Hi everyone. Can u help me with my problem?
enumer: checking package: report.go:4:2: could not import sync (type-checking package "sync" failed (/usr/local/go/src/sync/pool.go:9:2: could not import runtime (type-checking package "runtime" failed (/usr/local/go/src/runtime/mem_linux.go:21:6: sysAlloc redeclared in this block))))

**Comment by alvaroloes** [comment]
Hi

Could you please tell me which version of Go you were using Enumer with? Were you using go modules?

**Comment by alvaroloes** [comment]
@kochurovro This was probably caused because Enumer was incompatible with go modules. It is compatible now.
Please install the latest version by doing:
```
go get -u github.com/alvaroloes/enumer
```
You should not see that issue now.

Closing this. Reopen if it keeps showing
