### ISSUE TITLE
invalid cross-device link

### ISSUE THREAD

**Issue by robinknaapen** [alvaroloes/enumer#46]
When using enumer in a CI environment I encounter this issue.

```Bash
enumer: moving tempfile to output file: rename /tmp/SomeType_enumer_457916248 sometype_enumer.go: invalid cross-device link
```

Due to how the container is sandboxed, this is not possible in my case.

In my opinion this should be a setting?

**Comment by glowa001** [comment]
I have the same problem

**Comment by robinknaapen** [comment]
A workaround is to set `$TEMPDIR` to some accessible location eg: `export TEMPDIR=$HOME/tmp`

**Comment by alvaroloes** [comment]
🤔 This must be caused but the latest version which first creates the generated file to a temp file and the moves it.

Thanks for the workaround Robin

**Comment by osctobe** [comment]
This is caused by 2615c451cef481904bad24495084d0bfeeb5a3d1. It should generate the file as "output name" + random suffix (ideally using mkstemp() to avoid races, or at least put the temporary file in output dir).

**Comment by robinknaapen** [comment]
https://github.com/wercker/mhook/issues/12#issuecomment-490482426
