### ISSUE TITLE
writes to `<type>_enumer.go` by default, not `<type>_string.go`

### ISSUE THREAD

**Issue by wcarmon** [alvaroloes/enumer#52]
https://github.com/alvaroloes/enumer/blob/d27f80ae1221dbded6b497f18a1c1e669d005170/stringer.go#L51

**Comment by wcarmon** [comment]
https://github.com/alvaroloes/enumer/blob/master/stringer.go#L133

**Comment by alvaroloes** [comment]
Fixed! Thank you!
