### ISSUE TITLE
Use Semantic Versioning

### ISSUE THREAD

**Issue by THE108** [alvaroloes/enumer#9]
Hi!

I would like to suggest using Semantic Versioning for enumer's releases.

What do you think about it?

Thanks.

**Comment by alvaroloes** [comment]
Hi! I'm traveling right now. Off the top of my head, it seems like a good idea, but let me think more deeply about it next week.

Thanks!

**Comment by alvaroloes** [comment]
@THE108 Semantic version is now supported thanks to go modules

You can now install any Enumer version you want by doing:
```
go get github.com/alvaroloes/enumer@1.1.0
```
